server.port: 9003
spring.profiles.active: dev

eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    #当前应用名称
    name: apply
#mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml