spring:
  datasource:
    url: jdbc:mysql://cdb-6jylg03n.gz.tencentcdb.com:10058/jys_apply?useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: qq554600654
    driver-class-name: com.mysql.cj.jdbc.Driver
